### ISSUE TITLE
Bootstrapping 

### ISSUE THREAD

**Issue by mdennis10** [gruan01/Unity.WCF.4#1]
I'm getting the following error when I launch the WCT Test client

    The service type provided could not be loaded as a service because it does not have a default (parameter-less) constructor. 

I'm assuming that this is because Unity as not been bootstrap correctly although I have added my dependency configuration within WcfServiceFactory class. How can I solve this issue?

    public class WcfServiceFactory : UnityServiceHostFactory
    {
        protected override void ConfigureContainer(IUnityContainer container)
        {
            DependencyInjectionConfig.Configure(container);
            container.LoadConfiguration();
            MapConfig.Configure();
        }
    }

**Comment by gruan01** [comment]
Hello , 

From your description, I know your Service Impl has constructor with parameter , but not apply InjectionConstructor on it.

Please remove constructor's parameter or apply InjectionConstructorAttribute.

Thanks.

**Comment by mdennis10** [comment]
private readonly ISomeClass _someClass;

        [InjectionConstructor]
        public SomeService(ISomeClass someClass)
        {
            _someClass = someClass;
        }

Added the attribute you mention still getting the same problem

**Comment by mdennis10** [comment]
Found the problem. I was not bootstrapping WcfServiceFactory.
